spring:
  profiles:
    active: "dev"
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

datasource:
  url: jdbc:h2:mem:goods;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  platform: h2
  username: sa
  password:
  driverClassName: org.h2.Driver
  initialize: true
  sqlScriptEncoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
---

spring:
  profiles: dev

---

spring:
  profiles: test
---

spring:
  profiles: prod